# Generated by Django 5.0.4 on 2024-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
