# Generated by Django 5.0.4 on 2024-04-12 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_blogmodel_date_posted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='reactionmodel',
            unique_together={('user', 'blog')},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='commentor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactionmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reactionmodel',
            name='person',
        ),
    ]
