# Generated by Django 5.0.4 on 2024-04-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blogApp', '0004_remove_commentmodel_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='commentor',
        ),
        migrations.AlterUniqueTogether(
            name='reactionmodel',
            unique_together={('person', 'blog')},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_person', to='accounts.person'),
        ),
        migrations.AddField(
            model_name='reactionmodel',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.person'),
        ),
        migrations.RemoveField(
            model_name='reactionmodel',
            name='user',
        ),
    ]
