# Generated by Django 5.0.4 on 2024-04-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blogApp', '0005_remove_commentmodel_commentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionmodel',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.person'),
        ),
    ]
