# Generated by Django 5.0.4 on 2024-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0003_bookmodel_orimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='bookImages', verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='orImageUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Or Image URL'),
        ),
    ]
