# Generated by Django 5.0.4 on 2024-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0004_alter_bookmodel_bookimage_alter_bookmodel_orimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmodel',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
    ]
